apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
data:
  config.yaml: |
    model_list:
      - model_name: "gpt-4o"
        litellm_params:
          model: "openai/gpt-4o"
          api_key: "os.environ/OPENAI_API_KEY_1"
      - model_name: "gpt-4o"
        litellm_params:
          model: "openai/gpt-4o"
          api_key: "os.environ/OPENAI_API_KEY_2"
      - model_name: "claude-sonnet"
        litellm_params:
          model: "anthropic/claude-sonnet-4-5-20250929"
          api_key: "os.environ/ANTHROPIC_API_KEY"

    router_settings:
      routing_strategy: "least-busy"
      num_retries: 3
      fallbacks:
        - gpt-4o: ["claude-sonnet"]
